### 첨도와 왜도
- 첨도
    - 데이터 분포의 꼬리의 두꺼움을 나타내는 지표
    - 양의 첨도 : 분포의 꼬리가 두껍고, 중심에 더 많은 데이터가 몰려 있음
    - 0 첨도 : 정규 분포와 유사한 분포를 가짐
    - 음의 첨도 : 분포의 꼬리가 얇고, 데이터가 중심에서 퍼져있음
- 왜도
    - 데이터 분포의 비대칭성을 나타내는 지표
    - 양의 왜도 : 오른쪽 꼬리가 길고, 데이터가 왼쪽으로 치우쳐 있음
    - 0 왜도 : 데이터가 대칭적으로 분포
    - 음의 왜도 : 왼쪽 꼬리가 길고, 데이터가 오른쪽으로 치우쳐 있음

In [52]:
import numpy as np
import pandas as pd

df = pd.read_csv("dataset/주택 가격/train.csv")
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,968,20,RL,NaN,7390,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2008,WD,Normal,135000
1,739,90,RL,60.0,10800,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,3,2009,WD,Alloca,179000
2,696,20,RL,54.0,13811,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,7,2006,WD,Normal,176000
3,239,20,RL,93.0,12030,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2007,New,Partial,318000
4,891,50,RL,60.0,8064,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,Shed,2000,7,2007,WD,Normal,122900

In [53]:
# 수치형 데이터만 사용
df = df.select_dtypes(exclude='object')
df.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,968,20,NaN,7390,5,7,1955,1955,151.0,902,...,0,0,0,0,0,0,0,7,2008,135000
1,739,90,60.0,10800,5,5,1987,1988,0.0,1200,...,120,0,0,0,0,0,0,3,2009,179000
2,696,20,54.0,13811,6,6,1987,1987,72.0,980,...,125,0,0,0,0,0,0,7,2006,176000
3,239,20,93.0,12030,8,5,2007,2007,254.0,0,...,168,228,0,0,0,0,0,12,2007,318000
4,891,50,60.0,8064,5,7,1949,2006,0.0,0,...,0,0,0,0,0,0,2000,7,2007,122900

In [54]:
# 중앙값으로 결측치 채우기
df = df.fillna(value=df.median())

In [55]:
# 1. 왜도
skewness = df.skew()
ans = skewness.idxmax()
print(ans, skewness.max())

MiscVal 22.127461688829182

In [56]:
# 2. 첨도
kurtosis = df.kurt()
ans = kurtosis.idxmax()
print(ans, kurtosis.max())

MiscVal 569.1515180703144